#!/usr/bin/env python3
from sys import argv
from subprocess import run
from pathlib import Path


HERE = Path(__file__).parent
DAY = argv[1]

run(
    ['node', str(HERE / DAY)],
    env={'TQ_AOC_INPUT_FOLDER': str(HERE / 'inputs')}
)
